server:
  port: 10087 # 端口
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  client:
    #注释就会把自己也注册到注册中心
    #register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    #fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka # 配置其他Eureka服务的地址，而不是自己，比如10087